FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE config.settings.develop

# Set work directory
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gettext \
    && rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install Python dependencies
COPY requirements/base.txt /app/
COPY requirements/prod.txt /app/
RUN uv pip install --system --no-cache -r /app/prod.txt

# Create static and media directories if they don't exist
RUN mkdir -p /app/static /app/media

# Add entrypoint script
COPY entrypoint.dev.sh /app/
RUN chmod +x /app/entrypoint.dev.sh

# Set entrypoint
ENTRYPOINT ["/app/entrypoint.dev.sh"]

# Run development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8020"] 