# Generated by Django 5.2.1 on 2026-02-13 18:24

import apps.common.mixins
import apps.common.utils
import apps.common.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('about_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Haqida sarlavha')),
                ('about_title_uz', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Haqida sarlavha')),
                ('about_title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Haqida sarlavha')),
                ('about_title_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Haqida sarlavha')),
                ('about_description', models.TextField(blank=True, default='', verbose_name='Haqida tavsif')),
                ('about_description_uz', models.TextField(blank=True, default='', null=True, verbose_name='Haqida tavsif')),
                ('about_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Haqida tavsif')),
                ('about_description_en', models.TextField(blank=True, default='', null=True, verbose_name='Haqida tavsif')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Fon rasmi')),
            ],
            options={
                'verbose_name': 'Asosiy sozlamalar',
                'verbose_name_plural': 'Asosiy sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Qisqa tavsif')),
                ('short_description_uz', models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif')),
                ('short_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif')),
                ('short_description_en', models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.city', verbose_name='Tartib (parent)')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Qisqa tavsif')),
                ('short_description_uz', models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif')),
                ('short_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif')),
                ('short_description_en', models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Tavsif')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (lat)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (long)')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='main.city', verbose_name='Shahar')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.village', verbose_name='Tartib (parent)')),
            ],
            options={
                'verbose_name': 'Qishloq',
                'verbose_name_plural': 'Qishloqlar',
            },
            bases=(apps.common.mixins.SlugifyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('image', models.ImageField(upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.gallery', verbose_name='Tartib (parent)')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.village', verbose_name='Qishloq')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faoligi')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('comment_uz', models.TextField(null=True, verbose_name='Izoh')),
                ('comment_ru', models.TextField(null=True, verbose_name='Izoh')),
                ('comment_en', models.TextField(null=True, verbose_name='Izoh')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq ism")),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq ism")),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name="To'liq ism")),
                ('who', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim (kasbi, qishloq aholisi va h.k.)')),
                ('who_uz', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Kim (kasbi, qishloq aholisi va h.k.)')),
                ('who_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Kim (kasbi, qishloq aholisi va h.k.)')),
                ('who_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Kim (kasbi, qishloq aholisi va h.k.)')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.comment', verbose_name='Tartib (parent)')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.village', verbose_name='Qishloq')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
            },
        ),
    ]
