# Generated by Django 5.2.1 on 2026-02-17 18:48

import apps.common.utils
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='image',
            field=models.ImageField(default='', upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
