# Generated by Django 5.2.1 on 2026-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_village_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='activities',
            field=models.JSONField(blank=True, default=list, verbose_name='Faoliyatlar'),
        ),
        migrations.AddField(
            model_name='village',
            name='activities_en',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Faoliyatlar'),
        ),
        migrations.AddField(
            model_name='village',
            name='activities_ru',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Faoliyatlar'),
        ),
        migrations.AddField(
            model_name='village',
            name='activities_uz',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Faoliyatlar'),
        ),
        migrations.AddField(
            model_name='village',
            name='seo_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='SEO taglar'),
        ),
    ]
