# Generated by Django 5.2.1 on 2026-02-27 10:37

import apps.common.utils
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_activities_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='facebook_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Facebook havola'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Instagram havola'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.utils.generate_upload_path, validators=[apps.common.validators.file_size], verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='telegram_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Telegram havola'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='youtube_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='YouTube havola'),
        ),
    ]
